### PR TITLE
Add a CLI to use the script from command line.

### PR DESCRIPTION
**Pull request by erezlevanon**
Create a CLI in a different file to allow using the script from the command line.
The CLI uses the same default values but allows passing arguments for all parameters.
Input file is required and all else are optional (output file is derived from input file if not supplied).

Previous script functionality remains the same.

### CODE REVIEW

**Comment by erezlevanon** [comment]
image

**Comment by beeb** [comment]
Why not have everything in the same file? Seems like overkill to have an additional script for just parsing CLI arguments. If this is kept in the "if __name__ == '__main__'" section it would allow the same file to be used as a standalone script with arguments, as well as an imported module.

**Comment by erezlevanon** [comment]
> Why not have everything in the same file? Seems like overkill to have an additional script for just parsing CLI arguments. If this is kept in the "if **name** == '**main**'" section it would allow the same file to be used as a standalone script with arguments, as well as an imported module.

@beeb I generally agree, specifically in that case I wanted to preserve the current use method that allows changing the default values in the main script and running it either via command line or via running in the OS GUI by double clicking the script. If i'll change the current __name__="__main__" part in the main script this will not happen.

I assumed this behavior is meant to allow users who are not familiar with command line interfaces to use it as well.

I can add it to the main file, and if no arguments are passed use the constants from the file but i think this will make the CLI behavior really strange and unexpected for users who are familiar with CLIs.


@CNCKitchen WDYT?

**Comment by CNCKitchen** [comment]
Two files are fine for me. For the moment I'd like to keep it as simple as possible and even I often struggle with CLI.

**Review by CNCKitchen — APPROVED** [review]
Looks fine to me.

**Pull request merged**
